# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateField(auto_now=True)),
                ('asistio', models.BooleanField(default=False)),
                ('ha_pagado', models.BooleanField(default=False)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asistentes',
                'verbose_name': 'Asistente',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateField(auto_now=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Comentarioss',
                'verbose_name': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('resumen', models.TextField(max_length=255)),
                ('contenido', models.TextField()),
                ('lugar', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='eventos')),
                ('es_libre', models.BooleanField(default=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('numero_visitas', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Categoria')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'verbose_name': 'Evento',
            },
        ),
        migrations.AddField(
            model_name='comentarios',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Evento'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistente',
            name='evento',
            field=models.ManyToManyField(to='events.Evento'),
        ),
    ]
