# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=40),
        ),
    ]
