# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registro_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='ciudad',
            new_name='distrito',
        ),
        migrations.AlterField(
            model_name='registro',
            name='provincia',
            field=models.CharField(choices=[('Azángaro', 'Azángaro'), ('Carabaya', 'Carabaya'), ('Chucuito', 'Chucuito'), ('El Collao', 'El Collao'), ('Huancané', 'Huancané'), ('Lampa', 'Lampa'), ('Melgar', 'Melgar'), ('Moho', 'Moho'), ('Puno', 'Puno'), ('San Antonio de Putina', 'San Antonio de Putina'), ('San Román', 'San Román'), ('Sandia', 'Sandia'), ('Yunguyo', 'Yunguyo')], max_length=100),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Provincia'),
        ),
    ]
