# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161219_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.AddField(
            model_name='registro',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
