# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 03:02
from __future__ import unicode_literals

import apps.events.models.evento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20161220_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.events.models.evento.upload_location, width_field='width_field'),
        ),
    ]
